version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    ports:
     - "3000:3000"
    command: yarn start
  api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - '3001:3001'
    volumes: 
      - ./app:/app
      - app_node_modules:/app/node_modules
    command: yarn json-server
volumes:
  app_node_modules: